# Generated by Django 6.0.4 on 2026-05-11 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('alert', 'Alert'), ('urgent', 'Urgent'), ('announcement', 'Announcement')], default='normal', help_text='Type of notification.', max_length=20)),
                ('content', models.TextField(help_text='Notification message.')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(help_text='User who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who sent this notification (null for system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', '-created_at'], name='notificatio_receive_7c6c44_idx'), models.Index(fields=['receiver', 'is_read'], name='notificatio_receive_11bcf4_idx')],
            },
        ),
    ]
