# Generated by Django 6.0.4 on 2026-04-30 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the live section.', max_length=255)),
                ('category', models.CharField(choices=[('teaching_language', 'Teaching / Language'), ('tech_coding_ai', 'Tech / Coding / AI'), ('career_mentorship', 'Career / Mentorship'), ('mental_health', 'Mental Health'), ('creative_design', 'Creative / Design'), ('academic', 'Academic'), ('others', 'Others')], help_text='Category of the live section.', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the live section.')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Required skill level.', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('tr', 'Turkish')], help_text='Language of instruction.', max_length=10)),
                ('sessions_per_week', models.PositiveIntegerField(help_text='Number of sessions per week.')),
                ('session_duration', models.PositiveIntegerField(help_text='Duration of each session in minutes.')),
                ('duration_days', models.PositiveIntegerField(help_text='Total duration in days.')),
                ('ending_date', models.DateTimeField(help_text='Date and time when this live section ends.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', help_text='Current status of the live section.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this live section.', on_delete=django.db.models.deletion.CASCADE, related_name='live_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Section',
                'verbose_name_plural': 'Live Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(help_text='Title of the content.', max_length=255)),
                ('link', models.URLField(help_text='URL link to the content resource.', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_section', models.ForeignKey(help_text='Live section this content belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='live_sections.livesection')),
                ('user', models.ForeignKey(help_text='User who created this content.', on_delete=django.db.models.deletion.CASCADE, related_name='live_section_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Section Content',
                'verbose_name_plural': 'Live Section Contents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveSectionOfferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(blank=True, help_text='User who created this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_section_links_created', to=settings.AUTH_USER_MODEL)),
                ('live_section', models.ForeignKey(help_text='Live section being linked.', on_delete=django.db.models.deletion.CASCADE, related_name='offer_links', to='live_sections.livesection')),
                ('offer', models.ForeignKey(help_text='Offer being linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='live_section_links', to='posts.offer')),
            ],
            options={
                'verbose_name': 'Live Section-Offer Link',
                'verbose_name_plural': 'Live Section-Offer Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='livesection',
            index=models.Index(fields=['user', '-created_at'], name='live_sectio_user_id_422232_idx'),
        ),
        migrations.AddIndex(
            model_name='livesection',
            index=models.Index(fields=['category'], name='live_sectio_categor_2174dc_idx'),
        ),
        migrations.AddIndex(
            model_name='livesection',
            index=models.Index(fields=['status'], name='live_sectio_status_94bf52_idx'),
        ),
        migrations.AddIndex(
            model_name='livesection',
            index=models.Index(fields=['skill_level'], name='live_sectio_skill_l_09b1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='livesection',
            index=models.Index(fields=['language'], name='live_sectio_languag_7a0bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='livesection',
            index=models.Index(fields=['ending_date'], name='live_sectio_ending__9e6930_idx'),
        ),
        migrations.AddIndex(
            model_name='livesectioncontent',
            index=models.Index(fields=['live_section', 'created_at'], name='live_sectio_live_se_6e8262_idx'),
        ),
        migrations.AddIndex(
            model_name='livesectioncontent',
            index=models.Index(fields=['user'], name='live_sectio_user_id_16d2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='livesectionofferlink',
            index=models.Index(fields=['live_section'], name='live_sectio_live_se_c3082a_idx'),
        ),
        migrations.AddIndex(
            model_name='livesectionofferlink',
            index=models.Index(fields=['offer'], name='live_sectio_offer_i_943d1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='livesectionofferlink',
            unique_together={('live_section', 'offer')},
        ),
    ]
