# Generated by Django 6.0.4 on 2026-04-29 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the course.', max_length=255)),
                ('category', models.CharField(choices=[('teaching_language', 'Teaching / Language'), ('tech_coding_ai', 'Tech / Coding / AI'), ('career_mentorship', 'Career / Mentorship'), ('mental_health', 'Mental Health'), ('creative_design', 'Creative / Design'), ('academic', 'Academic'), ('others', 'Others')], help_text='Category of the course.', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the course.')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], help_text='Required skill level for the course.', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu'), ('ar', 'Arabic'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('zh', 'Chinese'), ('hi', 'Hindi'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ja', 'Japanese'), ('tr', 'Turkish')], help_text='Language of instruction.', max_length=10)),
                ('sessions_per_week', models.PositiveIntegerField(help_text='Number of sessions per week.')),
                ('session_duration', models.PositiveIntegerField(help_text='Duration of each session in minutes.')),
                ('course_duration_days', models.PositiveIntegerField(help_text='Total course duration in days.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', help_text='Current status of the course.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this course.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(help_text='Title of the content.', max_length=255)),
                ('link', models.URLField(help_text='URL link to the content resource.', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of the content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this content.', on_delete=django.db.models.deletion.CASCADE, related_name='course_contents', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course this content belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.course')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseOfferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course being linked.', on_delete=django.db.models.deletion.CASCADE, related_name='offer_links', to='courses.course')),
                ('linked_by', models.ForeignKey(help_text='User who created this link.', on_delete=django.db.models.deletion.CASCADE, related_name='course_links_created', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(help_text='Offer being linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='posts.offer')),
            ],
            options={
                'verbose_name': 'Course-Offer Link',
                'verbose_name_plural': 'Course-Offer Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', '-created_at'], name='courses_cou_user_id_225190_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category'], name='courses_cou_categor_fec4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['skill_level'], name='courses_cou_skill_l_7793fb_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['language'], name='courses_cou_languag_94bd99_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['course', 'created_at'], name='courses_con_course__d7ff07_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['user'], name='courses_con_user_id_6572bc_idx'),
        ),
        migrations.AddIndex(
            model_name='courseofferlink',
            index=models.Index(fields=['course'], name='courses_cou_course__17c7d7_idx'),
        ),
        migrations.AddIndex(
            model_name='courseofferlink',
            index=models.Index(fields=['offer'], name='courses_cou_offer_i_970ab6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseofferlink',
            unique_together={('course', 'offer')},
        ),
    ]
