# Generated by Django 6.0.4 on 2026-04-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseofferlink',
            name='linked_by',
            field=models.ForeignKey(blank=True, help_text='User who created this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_links_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
