# Generated by Django 6.0.4 on 2026-04-29 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(help_text='Name/title of the offer.', max_length=255)),
                ('category', models.CharField(choices=[('learn_language', 'Learn a Language'), ('learn_tech_ai', 'Learn Tech / AI'), ('career_cv_help', 'Career / CV Help'), ('mental_health_support', 'Mental Health Support'), ('academic_tuition', 'Academic Tuition'), ('creative_skill', 'Creative Skill'), ('others', 'Others')], help_text='Category of the offer.', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the offer.')),
                ('availability', models.CharField(choices=[('1_2_hours', '1 - 2 hours / week'), ('3_5_hours', '3 - 5 hours / week'), ('6_8_hours', '6 - 8 hours / week'), ('8_10_hours', '8 - 10 hours / week'), ('10_plus_hours', '10+ hours / week')], help_text='Weekly availability for this offer.', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', help_text='Current status of the offer.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this offer.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='posts_offer_user_id_ff3cde_idx'), models.Index(fields=['category'], name='posts_offer_categor_ba6d42_idx'), models.Index(fields=['status'], name='posts_offer_status_0d502a_idx'), models.Index(fields=['availability'], name='posts_offer_availab_694437_idx')],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(help_text='Name/title of the request.', max_length=255)),
                ('category', models.CharField(choices=[('learn_language', 'Learn a Language'), ('learn_tech_ai', 'Learn Tech / AI'), ('career_cv_help', 'Career / CV Help'), ('mental_health_support', 'Mental Health Support'), ('academic_tuition', 'Academic Tuition'), ('creative_skill', 'Creative Skill'), ('others', 'Others')], help_text='Category of the request.', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the request.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', help_text='Current status of the request.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this request.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='posts_reque_user_id_57419f_idx'), models.Index(fields=['category'], name='posts_reque_categor_e3c456_idx'), models.Index(fields=['status'], name='posts_reque_status_91a45e_idx')],
            },
        ),
    ]
