# Generated by Django 6.0.4 on 2026-05-01 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('job', 'Job Resources'), ('internship', 'Internship Resources'), ('scholarship', 'Scholarship Resources'), ('grant', 'Grant Resources'), ('fellowship', 'Fellowship Resources'), ('funding', 'Funding Resources'), ('volunteer', 'Volunteer Resources'), ('other', 'Other Resources')], max_length=20)),
                ('description', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Manager/admin/superuser who created this resource.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'), models.Index(fields=['user', '-created_at'], name='resources_r_user_id_77a633_idx')],
            },
        ),
    ]
